"""Pydantic schemas for the LLM Analysis and After Meeting module.

Defines request/response models for transcript analysis, meeting summaries,
action items, and LLM pipeline outputs.
"""

import uuid
import datetime as dt
from typing import Optional, List
from enum import Enum

from pydantic import BaseModel, Field, ConfigDict, field_validator


# ============================================
# ENUMS
# ============================================

class ActionItemPriority(str, Enum):
    high = "high"
    medium = "medium"
    low = "low"


class ActionItemStatus(str, Enum):
    pending = "pending"
    in_progress = "in_progress"
    completed = "completed"
    cancelled = "cancelled"


# ============================================
# ANALYSIS REQUEST / RESPONSE
# ============================================

class AnalysisRequest(BaseModel):
    """Optional parameters for triggering analysis."""
    reanalyze: bool = Field(
        False, description="Force re-analysis even if summary already exists"
    )


class AnalysisResponse(BaseModel):
    """Response after triggering or retrieving analysis."""
    meeting_id: uuid.UUID
    status: str = Field(description="Analysis status: completed, failed, no_transcript")
    summary: Optional["SummaryResponse"] = None
    action_items: List["ActionItemResponse"] = []
    llm_provider: Optional[str] = None
    llm_model: Optional[str] = None
    llm_tier: Optional[int] = None


# ============================================
# SUMMARY SCHEMAS
# ============================================

class SummaryResponse(BaseModel):
    """Meeting summary as generated by LLM."""
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    meeting_id: uuid.UUID
    summary_text: Optional[str] = None
    decisions: List[dict] = Field(default_factory=list)
    topics: List[dict] = Field(default_factory=list)
    speakers: List[dict] = Field(default_factory=list)
    llm_provider: Optional[str] = None
    llm_model: Optional[str] = None
    llm_tier: Optional[int] = None
    generated_at: dt.datetime


# ============================================
# ACTION ITEM SCHEMAS
# ============================================

class ActionItemResponse(BaseModel):
    """Action item as returned from the API."""
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    meeting_id: uuid.UUID
    task: str
    owner_id: Optional[uuid.UUID] = None
    owner_name: Optional[str] = None
    deadline: Optional[dt.date] = None
    priority: str
    status: str
    confirmed: bool
    confirmed_at: Optional[dt.datetime] = None
    source_quote: Optional[str] = None
    dependencies: Optional[str] = None
    completed_at: Optional[dt.datetime] = None
    created_at: dt.datetime
    updated_at: dt.datetime


class ActionItemUpdate(BaseModel):
    """Schema for updating an action item."""
    task: Optional[str] = Field(None, min_length=1)
    owner_name: Optional[str] = Field(None, max_length=255)
    deadline: Optional[dt.date] = None
    priority: Optional[ActionItemPriority] = None
    status: Optional[ActionItemStatus] = None
    confirmed: Optional[bool] = None
    dependencies: Optional[str] = None


# ============================================
# LLM STRUCTURED OUTPUT SCHEMAS
# (Expected JSON structures from the LLM)
# ============================================

class LLMDecision(BaseModel):
    """A key decision extracted by the LLM."""
    decision: str
    context: Optional[str] = None
    made_by: Optional[str] = None


class LLMActionItem(BaseModel):
    """An action item extracted by the LLM."""
    task: str
    owner: Optional[str] = None
    deadline: Optional[str] = None
    priority: str = "medium"
    source_quote: Optional[str] = None


class LLMTopic(BaseModel):
    """A discussion topic identified by the LLM."""
    topic: str
    summary: Optional[str] = None
    time_spent_estimate: Optional[str] = None


class LLMSpeaker(BaseModel):
    """Speaker contribution analysis from the LLM."""
    name: str
    role: Optional[str] = None
    contribution_summary: Optional[str] = None
    segment_count: Optional[int] = None


class LLMAnalysisOutput(BaseModel):
    """Complete structured output from the LLM analysis pipeline."""
    summary: str
    decisions: List[LLMDecision] = []
    action_items: List[LLMActionItem] = []
    topics: List[LLMTopic] = []
    speakers: List[LLMSpeaker] = []


# ============================================
# EXTRACTION ENGINE SCHEMAS
# ============================================

class ExtractionRequest(BaseModel):
    """Request to extract action items from a transcript."""
    replace_existing: bool = Field(
        False, description="Delete existing action items before extracting new ones"
    )


class ExtractionResponse(BaseModel):
    """Response from the action item extraction engine."""
    status: str
    items: List[ActionItemResponse] = []
    count: int = 0
    llm_provider: Optional[str] = None
    llm_model: Optional[str] = None


class BatchConfirmRequest(BaseModel):
    """Confirm multiple action items at once."""
    item_ids: List[uuid.UUID] = Field(..., min_length=1, description="Action item IDs to confirm")


class BatchRejectRequest(BaseModel):
    """Reject (delete) multiple action items at once."""
    item_ids: List[uuid.UUID] = Field(..., min_length=1, description="Action item IDs to reject/delete")


class BatchStatusRequest(BaseModel):
    """Update status for multiple action items."""
    item_ids: List[uuid.UUID] = Field(..., min_length=1)
    status: ActionItemStatus


class BatchConfirmResponse(BaseModel):
    """Response from batch confirm."""
    confirmed_count: int
    items: List[ActionItemResponse] = []


class BatchRejectResponse(BaseModel):
    """Response from batch reject."""
    rejected_count: int


class ActionItemSummaryResponse(BaseModel):
    """Summary counts for action items in a meeting."""
    total: int
    by_status: dict = {}
    by_priority: dict = {}
    confirmed: int
    unconfirmed: int
    owners: List[str] = []
